{% set name = "pymodrev" %}
{% set version = "1.0" %}
package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter >=0.6.3
    - modrev

about:
  home: https://github.com/Lourencom/pymodrev
  summary: 'Python interface for ModRev'
