package:
  name: 'pymodrev'
  version: 1.2

source:
  path: ../src/main/

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.10
    - setuptools

  run:
    - python
    - colomoto_jupyter
    - modrev
    - ginsim-python

about:
  home: https://github.com/Lourencom/pymodrev
  summary: 'Python interface for ModRev'
