{% set version = "1.0" %}
package:
  name: 'pymodrev'
  version: '{{ version }}'

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter
    - modrev

about:
  home: https://github.com/Lourencom/pymodrev
  summary: 'Python interface for ModRev'
